### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

In [73]:
'''
📘 What is NumPy?
NumPy (Numerical Python) is a powerful Python library used for scientific and numerical computing.

It provides:

✅ A fast, multidimensional array object called ndarray
✅ Functions to perform mathematical operations on arrays
✅ Tools for linear algebra, statistics, random number generation, Fourier transforms, and more
✅ Support for working with large datasets efficiently

'''

'\n📘 What is NumPy?\nNumPy (Numerical Python) is a powerful Python library used for scientific and numerical computing.\n\nIt provides:\n\n✅ A fast, multidimensional array object called ndarray\n✅ Functions to perform mathematical operations on arrays\n✅ Tools for linear algebra, statistics, random number generation, Fourier transforms, and more\n✅ Support for working with large datasets efficiently\n\n'

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [74]:
'''
🔄 NumPy Arrays vs Python Sequences (Lists, Tuples)
1️⃣ Size Flexibility
Python Lists:
✔️ Dynamic — You can change the size (append, remove)
❌ Less efficient for numerical computation

NumPy Arrays:
❌ Fixed size — Once created, cannot be resized directly
✔️ Efficient memory usage and fast operations
'''

'\n🔄 NumPy Arrays vs Python Sequences (Lists, Tuples)\n1️⃣ Size Flexibility\nPython Lists:\n✔️ Dynamic — You can change the size (append, remove)\n❌ Less efficient for numerical computation\n\nNumPy Arrays:\n❌ Fixed size — Once created, cannot be resized directly\n✔️ Efficient memory usage and fast operations\n'

In [75]:
'''
2️⃣ Data Type (dtype)
Python Lists:
✔️ Can hold mixed data types
❌ Slower for numeric processing

NumPy Arrays:
❌ Must be of the same data type (homogeneous)
✔️ Faster and takes less memory

python
Copy
Edit
'''

'\n2️⃣ Data Type (dtype)\nPython Lists:\n✔️ Can hold mixed data types\n❌ Slower for numeric processing\n\nNumPy Arrays:\n❌ Must be of the same data type (homogeneous)\n✔️ Faster and takes less memory\n\npython\nCopy\nEdit\n'

In [76]:
'''
3️⃣ Performance
NumPy arrays are way faster and more memory-efficient than Python lists for large data and mathematical operations.

Vectorized operations in NumPy allow batch processing without explicit loops.

python
Copy
Edit

'''

'\n3️⃣ Performance\nNumPy arrays are way faster and more memory-efficient than Python lists for large data and mathematical operations.\n\nVectorized operations in NumPy allow batch processing without explicit loops.\n\npython\nCopy\nEdit\n\n'

In [77]:
'''
4️⃣ Mathematical Power
NumPy provides a large number of built-in mathematical functions (like mean, std, sin, log, etc.)

Python lists require for loops or external functions.

python
Copy
Edit

'''

'\n4️⃣ Mathematical Power\nNumPy provides a large number of built-in mathematical functions (like mean, std, sin, log, etc.)\n\nPython lists require for loops or external functions.\n\npython\nCopy\nEdit\n\n'

In [78]:
'''
5️⃣ Used in Scientific Libraries
Libraries like Pandas, Scikit-Learn, TensorFlow, OpenCV, etc.
🔁 Accept Python lists but internally convert them to NumPy arrays.

'''

'\n5️⃣ Used in Scientific Libraries\nLibraries like Pandas, Scikit-Learn, TensorFlow, OpenCV, etc.\n🔁 Accept Python lists but internally convert them to NumPy arrays.\n\n'

### Creating Numpy Arrays

In [79]:
# Importing the NumPy library (used for numerical computations)
import numpy as np

# Creating a 1-dimensional NumPy array using a Python list
a = np.array([1, 2, 3])

# Printing the created NumPy array
print(a)


[1 2 3]


In [80]:

# 🌟 2D ARRAY EXAMPLE
# Creating a 2D NumPy array (matrix with rows and columns)
b = np.array([[1, 2, 3],
              [4, 5, 6]])

print("2D Array:")
print(b)


2D Array:
[[1 2 3]
 [4 5 6]]


In [81]:

# 🌟 Creating a 3D NumPy array
c = np.array([
                [[1, 2],
                 [3, 4]],

                [[5, 6],
                 [7, 8]]
             ])

print("3D Array:")
print(c)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [82]:
# Creating a NumPy array with specified data type as float
a = np.array([1, 2, 3], dtype=float)

print("Array with float dtype:")
print(a)


Array with float dtype:
[1. 2. 3.]


In [83]:
# Creating an array from 1 to 10 with step size of 2
a = np.arange(1, 11, 2)
print("Array using np.arange():")
print(a)


Array using np.arange():
[1 3 5 7 9]


In [84]:
# arange  with reshape
np.arange(16).reshape(2,2,2,2)




array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [85]:
# Create a 1D array of numbers from 0 to 15 (total 16 elements)
a = np.arange(16)

# Reshape the 1D array into a 4D array of shape (2, 2, 2, 2)
b = a.reshape(2, 2, 2, 2)

print("4D Reshaped Array:")
print(b)


4D Reshaped Array:
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [86]:
# Create a 2D array (matrix) of shape (3 rows, 4 columns) filled with 1s
ones_array = np.ones((3, 4))
print("Array of ones (3x4):")
print(ones_array)


Array of ones (3x4):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [87]:
np.zeros((3,4))# Create a 2D array of shape (3, 4) filled with 0s
zeros_array = np.zeros((3, 4))
print("Array of zeros (3x4):")
print(zeros_array)


Array of zeros (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [88]:

# Create a 2D array of shape (3, 4) filled with random float numbers between 0 and 1
arr = np.random.random((3, 4))
print("Random array (3x4):")
print(arr)


Random array (3x4):
[[0.18426825 0.35937586 0.69251514 0.72119077]
 [0.70252618 0.41600816 0.34709399 0.84734577]
 [0.36132877 0.37586105 0.00546596 0.54077535]]


In [89]:
# Create 10 equally spaced numbers between -10 and 10
a = np.linspace(-10, 10, 10)
print("Equally spaced values (float):")
print(a)


Equally spaced values (float):
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [90]:
# np.identity
np.identity(3)# Create a 3x3 identity matrix
a = np.identity(3)
print("3x3 Identity Matrix:")
print(a)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Array Attributes

In [91]:
# 1D array of 10 integers
a1 = np.arange(10, dtype=np.int32)
# Output: [0 1 2 3 4 5 6 7 8 9]

# 2D array of shape (3, 4) with float values from 0 to 11
a2 = np.arange(12, dtype=float).reshape(3, 4)
# Output:
# [[ 0.  1.  2.  3.]
#  [ 4.  5.  6.  7.]
#  [ 8.  9. 10. 11.]]

# 3D array of shape (2, 2, 2) with integers from 0 to 7
a3 = np.arange(8).reshape(2, 2, 2)
print("3D array (a3):")
print(a3)


3D array (a3):
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [92]:
# ndim
a3.ndim

#. tells about the direction

3

In [93]:
import numpy as np  # Importing numpy library

# Creating a 3D array with shape (2, 2, 2)
a3 = np.arange(8).reshape(2, 2, 2)

# Displaying the array
print("Array a3:")
print(a3)

# Checking the shape of the array
print("\nShape of a3:")
print(a3.shape)  # Output: (2, 2, 2)


Array a3:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Shape of a3:
(2, 2, 2)


In [94]:
# Array a2 is already created with shape (3, 4)
# Means: 3 rows × 4 columns = 12 elements total

# .size → total number of elements in the array
print("Total number of elements in a2:", a2.size)

# Also print the array to verify
print("Array a2:")
print(a2)


Total number of elements in a2: 12
Array a2:
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [95]:
# itemsize
# Getting the total number of elements using .size
print("\nTotal number of elements in a2:")
print(a2.size)  # Output: 12



Total number of elements in a2:
12


In [96]:
# Assume: np already imported and a1, a2, a3 arrays already created like below:

# a1: 1D array of integers (int32)
a1 = np.arange(10, dtype=np.int32)

# a2: 2D array of floats (float64)
a2 = np.arange(12, dtype=float).reshape(3, 4)

# a3: 3D array of default integers (int64, depending on system)
a3 = np.arange(8).reshape(2, 2, 2)

# Checking data types of each array
print("Data type of a1:", a1.dtype)  # int32
print("Data type of a2:", a2.dtype)  # float64
print("Data type of a3:", a3.dtype)  # int64 (default for np.arange)


Data type of a1: int32
Data type of a2: float64
Data type of a3: int64


### Changing Datatype

In [97]:
# Assume a3 already created like this:
a3 = np.arange(8).reshape(2, 2, 2)  # Default dtype is usually int64

# Convert a3 to int32 (32-bit integer) using astype
a3_converted = a3.astype(np.int32)

print("Original dtype of a3:", a3.dtype)          # Usually int64
print("Converted dtype of a3_converted:", a3_converted.dtype)  # Now int32



Original dtype of a3: int64
Converted dtype of a3_converted: int32


### Array Operations

In [98]:
# Create a 3x4 array with values from 0 to 11
a1 = np.arange(12).reshape(3, 4)

# Create another 3x4 array with values from 12 to 23
a2 = np.arange(12, 24).reshape(3, 4)

# Print the second array
print("Array a2:")
print(a2)


Array a2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [99]:
# a1 is a 3x4 array with values from 0 to 11
# Let's square each element using scalar operation

print("Original a1 array:")
print(a1)

# Perform element-wise square operation
print("\nSquared a1 (a1 ** 2):")
print(a1 ** 2)


Original a1 array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Squared a1 (a1 ** 2):
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [100]:
# relational
a2 == 15# a2 is already defined as:
# [[12 13 14 15]
#  [16 17 18 19]
#  [20 21 22 23]]

# Check which elements in a2 are equal to 15
print("Relational check (a2 == 15):")
print(a2 == 15)


Relational check (a2 == 15):
[[False False False  True]
 [False False False False]
 [False False False False]]


In [101]:
# a1 and a2 must be of the same shape
# a1 = [[ 0  1  2  3]
#       [ 4  5  6  7]
#       [ 8  9 10 11]]

# a2 = [[12 13 14 15]
#       [16 17 18 19]
#       [20 21 22 23]]

# Element-wise exponentiation: a1 ** a2
print("a1:")
print(a1)

print("\na2:")
print(a2)

print("\nElement-wise power (a1 ** a2):")
print(a1 ** a2)


a1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Element-wise power (a1 ** a2):
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


### Array Functions

In [102]:
# Step 1: Generate a 3x3 matrix with random float values between 0 and 1
a1 = np.random.random((3, 3))

# Step 2: Multiply each element by 100 to scale to 0–100 range
a1 = a1 * 100

# Step 3: Round the values to nearest integer
a1 = np.round(a1)

# Final output
print("Random 3x3 matrix with values between 0–100:")
print(a1)


Random 3x3 matrix with values between 0–100:
[[10. 36. 87.]
 [17. 42. 71.]
 [80. 84.  7.]]


In [103]:
# a1: matrix hona chahiye, jisme hum axis=0 (column-wise) operation kar rahe hain

# Column-wise product (axis=0)
print("Column-wise Product:")
print(np.prod(a1, axis=0))  # Each column ke values ka product

# Row-wise product (axis=1)
print("\nRow-wise Product:")
print(np.prod(a1, axis=1))  # Each row ke values ka product

# Matrix also print kar dete hain for reference
print("\nOriginal Matrix (a1):")
print(a1)


Column-wise Product:
[ 13600. 127008.  43239.]

Row-wise Product:
[31320. 50694. 47040.]

Original Matrix (a1):
[[10. 36. 87.]
 [17. 42. 71.]
 [80. 84.  7.]]


In [104]:
# Mean (average) of each row
print("Row-wise Mean:")
print(np.mean(a1, axis=1))  # axis=1 → row-wise

# Median of each row
print("\nRow-wise Median:")
print(np.median(a1, axis=1))

# Standard Deviation (spread of data)
print("\nRow-wise Standard Deviation:")
print(np.std(a1, axis=1))

# Variance (square of std)
print("\nRow-wise Variance:")
print(np.var(a1, axis=1))

# Reference matrix
print("\nOriginal Matrix (a1):")
print(a1)


Row-wise Mean:
[44.33333333 43.33333333 57.        ]

Row-wise Median:
[36. 42. 80.]

Row-wise Standard Deviation:
[31.98263418 22.06555888 35.39303133]

Row-wise Variance:
[1022.88888889  486.88888889 1252.66666667]

Original Matrix (a1):
[[10. 36. 87.]
 [17. 42. 71.]
 [80. 84.  7.]]


In [105]:
# trigonomoetric functions
np.sin(a1)

array([[-0.54402111, -0.99177885, -0.82181784],
       [-0.96139749, -0.91652155,  0.95105465],
       [-0.99388865,  0.73319032,  0.6569866 ]])

In [106]:


# Create two compatible matrices
a2 = np.arange(12).reshape(3,4)     # Shape: (3, 4)
a3 = np.arange(12,24).reshape(4,3)  # Shape: (4, 3)

# Dot Product
result = np.dot(a2, a3)

print("a2 shape:", a2.shape)
print("a3 shape:", a3.shape)
print("Dot Product Result:\n", result)


a2 shape: (3, 4)
a3 shape: (4, 3)
Dot Product Result:
 [[114 120 126]
 [378 400 422]
 [642 680 718]]


In [107]:
# log and exponents

# Random 3x3 matrix (already done before)
a1 = np.random.random((3, 3))
a1 = np.round(a1 * 5, 2)   # Keep values smaller for better output
print("Original a1:\n", a1)

# Apply exponential function
exp_result = np.exp(a1)
print("\nExponential of a1:\n", exp_result)


Original a1:
 [[1.47 3.3  0.21]
 [2.35 4.59 3.67]
 [3.87 0.98 1.36]]

Exponential of a1:
 [[ 4.34923514 27.11263892  1.23367806]
 [10.48556972 98.49443016 39.25190586]
 [47.94238608  2.66445624  3.8961933 ]]


In [108]:
import numpy as np

# Generate random 2x3 array and scale it (0 to 100)
arr = np.random.random((2, 3)) * 100
print("Original Array:\n", arr)

# Round to nearest integer
rounded = np.round(arr)
print("\nRounded:\n", rounded)

# Floor: round down to nearest integer
floored = np.floor(arr)
print("\nFloored:\n", floored)

# Ceil: round up to nearest integer
ceiled = np.ceil(arr)
print("\nCeiled:\n", ceiled)


Original Array:
 [[51.84032138 76.88979553 46.42833954]
 [66.11260218 77.76873567 27.60484811]]

Rounded:
 [[52. 77. 46.]
 [66. 78. 28.]]

Floored:
 [[51. 76. 46.]
 [66. 77. 27.]]

Ceiled:
 [[52. 77. 47.]
 [67. 78. 28.]]


### Indexing and Slicing

In [109]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [110]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
a2[1,0]

np.int64(4)

In [113]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [114]:
a3[1,0,1]

np.int64(5)

In [115]:
a3[1,1,0]

np.int64(6)

In [116]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a1[2:5:2]

array([2, 4])

In [118]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [120]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [121]:
a2[1,::3]

array([4, 7])

In [122]:
a2[0,:]

array([0, 1, 2, 3])

In [123]:
a2[:,2]

array([ 2,  6, 10])

In [124]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [125]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [126]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [127]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [128]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [129]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [130]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [132]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [133]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [134]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [135]:
# reshape

In [136]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [137]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [138]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [139]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [140]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [141]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [142]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [ ]:
a5

In [ ]:
np.vsplit(a5,2)